### ISSUE TITLE
Add taxonomy to examples, index it and add as facet

### ISSUE THREAD

**Issue by daliboris** [eeditiones/tei-publisher-app#101]
Prepare some basic taxonomy for examples distributed with TEI Publisher. Something like 

- pictures
- IIIF
- translation
- annotation
- dictionary
- segmentation
- ...

Referr and use this taxonomy within distributed sample documents.

Index this taxonomy and add facet to filter examples in `tests` collection.

**Comment by tuurma** [comment]
Cool idea @daliboris! I think that "dictionary" probably should go into the `genre` facet, while others probably into a new facet, shall we call it `features`?

**Comment by daliboris** [comment]
I agree, the distinction between (literary) genre and edition feature makes sense. 

Calling it `fature` in singular with multiple values would be analogous to the facet `genre`.

**Comment by tuurma** [comment]
Coming in Publisher 8! :-) We'll have Feature, Period and Form as new facets



![Image](https://user-images.githubusercontent.com/449468/223173984-27b7d48c-b675-44cb-bc09-6e458a32ae93.png)
