### ISSUE TITLE
After Update to 7.1: An error occurred ...

### ISSUE THREAD

**Issue by ksbbf** [eeditiones/tei-publisher-app#103]
We updated our teipublisher app (7.0), following the [documention](https://teipublisher.com/exist/apps/tei-publisher/doc/documentation.xml?odd=docbook.odd&id=upgrade71). We only changed those files, which are mentioned there.

Unfortunately, we get an unspecific error when we try to access our tei-documents. They are stored in a separate exist-application. 
In our existdb request log we found an 500 message.

How can we get more specific error-messages? Is it possible to display the whole xquery-message in the error-template:

`<pre class="error templates:error-description"/>`

thanks

**Comment by wolfgangmm** [comment]
It depends on where exactly the error is triggered, but it sometimes helps to change `modules/lib/api.json` and remove the line:

```"x-error-handler": "vapi:handle-error",```

from the rules targeting `"/{docid}"` or `"/{file}.html"`. This will disable the error handling and reveal the underlying error. The error reporting will hopefully improve with the next release.

**Comment by ksbbf** [comment]
Thanks for your quick response!!

This is what we get:

`No template function found for call browse:fix-links (Max arity of 20 has been exceeded in searching for this template function. If needed, adjust $templates:MAX_ARITY in the templates.xql module.) [at line 190 of /opt/existdb5/data/expathrepo/templating-1.0.4/content/templates.xqm] `

We have an 5.2 existdb running the apps. In our teipublisher 7.1-apps we don't get this error.
