### ISSUE TITLE
"Playground" is broken

### ISSUE THREAD

**Issue by Conal-Tuohy** [eeditiones/tei-publisher-app#11]
https://teipublisher.com/exist/apps/tei-publisher/index.html?tab=0&collection=playground

**Comment by Conal-Tuohy** [comment]
exerr:ERROR source for module /db/apps/tei-publisher/transform/kreuzherren-web-main.xql not found in database [at line 115, column 9, source: /home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/tei-publisher-lib-2.8.8/content/util.xql] In function: pmu:process(xs:string, node()*, xs:string, xs:string, xs:string, element()?, map(*)?) [16:9:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/tei-publisher-lib-2.8.8/content/util.xql] pm-config:process(node()*, map(*)?, xs:string?, xs:string) [-1:-1:/db/apps/tei-publisher/modules/pm-config.xql] partial2032554254(node()*, map(*)?, xs:string?) [8:46:/db/apps/tei-publisher/modules/pm-config.xql] app:short-header(node(), map(*)) [-1:-1:/db/apps/tei-publisher/modules/lib/browse.xql] templates:process-output(element(), map(*), item()*, element()) [211:9:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:call(item(), element(), map(*)) [137:36:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:process(node()*, map(*)) [148:81:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:process(node()*, map(*)) [148:81:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:process(node()*, map(*)) [177:17:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] app:browse(node(), map(*), xs:int, xs:int, xs:string?) [-1:-1:/db/apps/tei-publisher/modules/lib/browse.xql] templates:process-output(element(), map(*), item()*, element()) [211:9:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:call(item(), element(), map(*)) [137:36:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:process(node()*, map(*)) [237:13:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:process-output(element(), map(*), item()*, element()) [211:9:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:call(item(), element(), map(*)) [137:36:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:process(node()*, map(*)) [80:13:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] app:is-writeable(node(), map(*), xs:string) [-1:-1:/db/apps/tei-publisher/modules/lib/browse.xql] templates:process-output(element(), map(*), item()*, element()) [211:9:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:call(item(), element(), map(*)) [137:36:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:process(node()*, map(*)) [133:51:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:process(node()*, map(*)) [90:9:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql] templates:apply(node()+, function(*), map(*)?, map(*)?) [69:13:/home/developer/teipublisher.com/exist-distribution-5.2.0/etc/../data/expathrepo/shared-0.8.4/content/templates.xql]

**Comment by wolfgangmm** [comment]
Some generated files were deleted. Fixed by recompiling all ODDs.
