### ISSUE TITLE
List headers are not rendered in epub

### ISSUE THREAD

**Issue by ccheraa** [eeditiones/tei-publisher-app#118]
When you generate an epub, a `head` element inside  a`list` element should be rendered as the list's header, however, it will be omitted

When you use this code to generate an epub:

```xml
<list>
    <head>head</head>
    <item>item 1</item>
    <item>item 2</item>
    <item>item 3</item>
</list>
```

**Actual result:**
```html
<ul class="tei-list2">
    <li class="tei-item">item 1</li>
    <li class="tei-item">item 2</li>
    <li class="tei-item">item 3</li>
</ul>
```

**Expected result:**
```html
<ul class="tei-list2">
    <li class="tei-head5">head</li>
    <li class="tei-item">item 1</li>
    <li class="tei-item">item 2</li>
    <li class="tei-item">item 3</li>
</ul>
```

**Comment by tuurma** [comment]
This is an ODD issue, not TEI Publisher as such. There's no guarantee that the teiSimplePrint odd covers all cases correctly and it's TEI consortium's responsibility, if anyone's.
