### ISSUE TITLE
Second instance of annotation mis-placed

### ISSUE THREAD

**Issue by GilShalit** [eeditiones/tei-publisher-app#122]
At least two annotation types (**Abbreviation** and **Regularization**) have a problem in their implementation.

To reproduce, open a file in the annotation samples of the TEI-Publisher annotate samples collection, either locally or on the [server](https://teipublisher.com/exist/apps/tei-publisher/annotate/3267.docx.xml?tab=0).  The steps below are for 3267.

1. Highlight the word domino, select the Regularization annotation, enter 'dom' as the regularization value. save the annotation and then save changes.  The annotation is fine.
2. Delete this annotation and save changes.
3. Highlight a word that comes *before* domino, e.g. 'Christo', select the Regularization annotation, enter 'chr' as the regularization value. save the annotation and then save changes.  The annotation is fine.
4. Highlight again the word domino, select the Regularization annotation, enter 'dom' as the regularization value. save the annotation and then save changes.  *The annotation is not OK - it is placed a little later in the line!*

Some notes:

1. After placing the second annotation (step 4), saving it but not all changes, the annotation is placed correctly in the main pane, but inspecting the TEI tab shows that the second annotation is already placed incorrectly. After saving changes and inspecting the XML, this is what is saved to file.
2. The same behavior happens for the Abbreviation annotation.  On the other hand, the **Sic** annotation works just fine, as do other annotations I tested.  I could not find a difference between Abbreviation and Regularization on the one hand and sic on the other, in the way they are declared in annotate.html and annotation-config.xqm.
3. Some custom annotations I created produce the wrong behavior of Abbreviation and Regularization.

**Comment by line-o** [comment]
It would be valuable to see if there are differences in the markup created.

**Comment by rowissmann** [comment]
There is a bug in modules/lib/api/annotations.xql
Change line 353 to:
`let $primary := $node/tei:sic | $node/tei:abbr | $node/tei:orig`

**Comment by GilShalit** [comment]
Just wanted to confirm that @rowissmann's fix does solve the reported issue. I guess this can be closed but maybe only after making the change in the distribution package.

**Comment by joewiz** [comment]
This is great news!

@rowissmann Could you confirm that you mean this line? https://github.com/eeditiones/tei-publisher-app/blob/master/modules/lib/api/annotations.xql#L370

**Comment by GilShalit** [comment]
I am attaching the image @rowissmann put in the slack channel, with the highlighted line that needed replacing.  It seems there have been some other changes to the module since the current distribution was finalized for v 7.1.

![image](https://user-images.githubusercontent.com/34002589/186090535-06d6cba3-1f0c-483f-8100-b602def40007.png)

**Comment by line-o** [comment]
Looking the current line

https://github.com/eeditiones/tei-publisher-app/blob/3d38420603d672c37bb08259f71253e2125b2f4c/modules/lib/api/annotations.xql#L370

the fix is to add more `tei:orig` to the union as suggested by @rowissmann 

```xquery
let $primary := $node/tei:sic | $node/tei:abbr | $node/tei:orig
```

I will open a PR if @rowissmann or someone else does not beat me  ;)
