### ISSUE TITLE
tei publisher not installing using existdb's package manager

### ISSUE THREAD

**Issue by dmgustavhi** [eeditiones/tei-publisher-app#123]
Not sure if this is an issue with tei publisher or existdb, but I thought I'd start here. I can't get tei publisher to install using existdb's package manager. The package manager says that the install was successful, but when I switch to the installed packages only the processing model libraries are installed (and tei publisher is once again listed as not installed). Other apps seem to install without issue. So far I've tried restarting existdb, clearing my cache, and uninstalling and reinstalling existdb. I've also searched for an .xar file I could upload directly, but I can't seem to find one. Any advice?

**Comment by wolfgangmm** [comment]
Which eXist-db version are you using?

You can download a .xar from here: https://exist-db.org/exist/apps/public-repo/public/tei-publisher-7.1.0.xar

**Comment by joewiz** [comment]
The problem may be that TEI Publisher v7 has a dependency on the `oas-router` package. If you don't see this package listed in your Package Manager's list of installed library packages, install it via the Package Manager. It's also available for download via the Public Repo at https://exist-db.org/exist/apps/public-repo/packages/oas-router. (For more info on this issue, see #121.)

**Comment by dmgustavhi** [comment]
Installing the oas-router package did the trick. Thanks for your help!
