### ISSUE TITLE
Doubled Content when using modelSequence wih pb-facs-link and pb-highlight

### ISSUE THREAD

**Issue by gillesbuelow** [eeditiones/tei-publisher-app#132]
I am using pb-grid to synchronize master-edition, facsimile and another text stage. I use seg-elements to point to zones in facsimile and by using pb-facs-link the zones will be shown in facsimile when hovering a corresponding line. I indipendantly used the same seg-elements to show a synchronized hihglight by using pb-highligth, works fine too.
But when I wish to combine these two features by using a modelSequence, the features itselfs work technically but I have doubled content shown per line. How to get it worked without doubleing the content of each edition?

**Comment by tuurma** [comment]
@gillesbuelow sorry not to get back to you earlier /o\

Anyway, your issue (I hope solved by now!) is not an issue with a TEI Publisher, but a question for advice, therefore should be really asked on Slack or the mailing list. I would recommend using a `pb-template` to construct all required output in one go or, alternatively, to adjust the `content` parameter for some of the models in your sequence to avoid duplicating the content.
