### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by nthieberger** [eeditiones/tei-publisher-app#14]
Hi, teipublisher isn't working right now?

**Comment by wolfgangmm** [comment]
Thanks for reporting. It should be back up again.

**Comment by nthieberger** [comment]
Can I ask if TeiPublisher requires images to be in a IIIF server? I have tried pointing at jpg files on http but the image is not retrieved?

**Comment by wolfgangmm** [comment]
You may set attribute `@type="image"` on the `pb-facsimile` component to display images from a normal URL not served via IIIF. The downside is that scaling will be done client-side, which is not efficient for really large images.

**Comment by nthieberger** [comment]
Hi,

Thanks for your reply. However, adding type="image" doesn't work,  it looks
like the IIF server is invoked, maybe in the ODD, so is there a way to
circumvent it and point at jpg files?

<pb-facsimile id="facsimile" base-uri="
https://apps.existsolutions.com/cantaloupe/iiif/2/" default-zoom-level="0"
show-navigation-control="show-navigation-control"
show-navigator="show-navigator" subscribe="transcription"></pb-facsimile>

Nick
