### ISSUE TITLE
issues uploading documents in playground 

### ISSUE THREAD

**Issue by rerouj** [eeditiones/tei-publisher-app#145]
Hi,

I'm new with TEI publisher, I was trying to add a new document in the "playground" collection but nothing appends. More precisely, the document is well uploaded in the existdb database but the document is not displayed on the TEI Publisher UI. 

Also, after uploading the document, a link is displayed on the upload box. When I press the link, an error page is displayed with the following message:

```
the server did not return any content

The request to the server failed.: Document playground/tei_output.xml not found [at line 452 of /db/apps/tei-publisher/modules/lib/api/document.xql]

the server did not return any content

The request to the server failed.: Document playground/tei_output.xml not found [at line 452 of /db/apps/tei-publisher/modules/lib/api/document.xql]
```

I suspect some sort of user privileges error, because the document is in the database, but the system for a certain reason can't access it.

Issue is observed in the following environnements:

- Apple M1 
- Apple Intel 
- docker deployment (Apple M1 host)

I don't know if the project is still maintained (no new issues from 2021...) but I hope somebody could bring me some help.

**Comment by tuurma** [comment]
@rerouj can you check, i.e. via eXide where in the collection structure of the database the file is uploaded and what are the privileges? Which user do you log in as, tei-demo or tei?

**Comment by rerouj** [comment]
@tuurma it's in ```/db/apps/tei-publisher/data/playground```. I've tried with both account.

<img width="759" alt="Screenshot 2023-03-03 at 12 57 38" src="https://user-images.githubusercontent.com/32023737/222716709-9aeed6b7-598e-40c2-a96e-3db572b3e2db.png">

**Comment by tuurma** [comment]
This looks legit. I'd suggest following further diagnostics:

1. Can you check the content of the file, in particular the namespace? 
2. If you check the Network tab in your browser when opening the Playground collection in Publisher, are there any errors?

**Comment by rerouj** [comment]
Well, I didn't realize that TEIpublisher was expecting documents complying with TEI guidelines... my xml used to have a bunch of TEI elements and the good namespace but was not well formed. 

I have tried again with a more standard TEI document and now it works.

Thank's for your help!
