### ISSUE TITLE
Odd behaviour in visual ODD editor of 6.0.0

### ISSUE THREAD

**Issue by maniku1976** [eeditiones/tei-publisher-app#17]
An app updated to 6.0.0 about a week ago, issue noticed on 2020-08-27. ODD file is attached.

[kivi.zip](https://github.com/eeditiones/tei-publisher-app/files/5139940/kivi.zip)

Any changes made to any model in the visual ODD editor of 6.0.0, e.g. changing a rendition slightly, and saving changes appears to screw up the way the element is displayed, as if the element had no rendition set at all. Any subsequent changes, including undoing the change made earlier, have no effect. Looking at the css file corresponding to the ODD file under /transform, the css classes for the edited models appear with :null, e.g.: .tei-note2:null {...}. Removing the :null manually causes the changes to take effect and the display of the elements to be otherwise restored. But if one then goes back to the visual ODD editor and simply presses save again, the issue comes back, with the :null in the css classes visible again. The issue does not occur when editing the ODD file in eXide.

**Comment by maniku1976** [comment]
Edit, on August 31, 2020: it appears that at least in the case of my ODD file, leaving scope for output rendition blank is what causes the :null for the classes in the css and the rendition specifications to be ignored. The same appears as as scope="null" in the outputRendition tags in the ODD file.

**Comment by wolfgangmm** [comment]
Version 1.2.3 of https://github.com/eeditiones/tei-publisher-components should fix the issue. Note that you can update your instance of TEI Publisher without having to reinstall:

1. go to eXide, login in as user "admin", open the main configuration which can be found in `apps/tei-publisher/modules/config.xqm`
2. change line 39 to read: `declare variable $config:webcomponents := "1.2.3";`
3. reload the ODD editor by holding shift and clicking on the browser's reload button
