### ISSUE TITLE
Bug ? : Agg Generator not functionning after upgrading Processing Model Libraries

### ISSUE THREAD

**Issue by Nepomucene-s** [eeditiones/tei-publisher-app#209]
It appears to me as a bug but maybe I do not understand the "version structure" of the software.

So I built the "latest" version of TEI Publisher via Docker.
In the Package Manager of the eXistdb server, I upgraded "TEI Publisher: Processing Model Libraries" from 3.0.0 to 4.0.0.
Then, the App Generator in the TEI Publisher app stopped working.

The server logs say :
```
[qtp2079051109-31] WARN  (TransactionManager.java [close]:421) - Transaction was not committed or aborted, auto aborting! 
[qtp2079051109-31] ERROR (LogFunction.java [writeLog]:199) - (Line: 521 /exist/etc/../data/expathrepo/roaster-1.8.0/content/router.xql) [c08c1ae4-0ec2-4636-8c1a-e40ec2f63685] post /api/apps/generate: 500
{"code":"experr:EXPATH00","description":null,"value":"Package requires version 3 of package http://existsolutions.com/apps/tei-publisher-lib. Installed version is 4.0.0. Please upgrade!","module":"/db/apps/tei-publisher/modules/lib/api/generate.xql","line":514,"column":9}
```
It clearly points to the Processing Model Libraries. Again, maybe it is a known behavior but it seems strange to me, hence the issues.

It's very easy to reproduce this behavior by the way.

Hope this helps.

**Comment by wolfgangmm** [comment]
The app generator still sets a dependency on tei-publisher-lib 3 in the generated `expath-pkg.xml`. To fix this until the next version of TP is out, you may change the dependency declaration in `modules/lib/api/generate.xql`, see variable `$deploy:EXPATH_DESCRIPTOR`:

```xml
<dependency package="http://existsolutions.com/apps/tei-publisher-lib" semver="4"/>
```
