### ISSUE TITLE
playground not playing

### ISSUE THREAD

**Issue by nthieberger** [eeditiones/tei-publisher-app#25]
I uploaded a file "Otto Rank" and its name appears in the list, but it is not clickable and so I can't see it in TeiPublisher.

**Comment by wolfgangmm** [comment]
This happens because `fileDesc/titleStmt/title` is empty. The link to the document is there, but has an empty string as content ;-) I changed the title via eXide to "Otto Rank" and now it shows up.

**Comment by nthieberger** [comment]
Thanks!
