### ISSUE TITLE
Toolbar button to return to collection

### ISSUE THREAD

**Issue by wolfgangmm** [eeditiones/tei-publisher-app#26]
If you browse into a collection, view a document and then want to go back to the collection, you don't have a way to do it directly. Would be nice to have a separate button in the toolbar (or menu) to bring you back into the collection you were browsing previously.

**Comment by plutonik-a** [comment]
@wolfgang I have solved this problem in a customised app by adding breadcrumbs for all levels, starting with a "home" link breadcrumb for the root level, then the collection name link as the following level and after that all the sublevels of the document pages.
This is a very common and intuitive UI/UX pattern I would definitely like to see in per default in the TEI-Publisher, too.
