### ISSUE TITLE
Untranslated labels

### ISSUE THREAD

**Issue by daliboris** [eeditiones/tei-publisher-app#27]
I've found these untranslated labels within Czech UI.

- [x] Settings
- [x] Regenerate All ODDs (Slow)
- [x] Filter

They can be reached from **index.html?tab=0** page.

I didn't found these strings in [Crowdin](https://crowdin.com/translate/tei-publisher/2/en-cs).

### Settings CZ
![Untranslated-text-Settings-CZ](https://user-images.githubusercontent.com/8056045/95114359-19fb4400-0744-11eb-84f8-0fea24a20617.png)
### Settings EN
![Untranslated-text-Settings-EN](https://user-images.githubusercontent.com/8056045/95114362-1a93da80-0744-11eb-8509-3d13269e4f64.png)

### Regenrate CZ
![Untranslated-text-Regenrate-all-ODDs-CZ](https://user-images.githubusercontent.com/8056045/95114375-1f588e80-0744-11eb-801f-bf99682c9f01.png)
### Regenrate EN
![Untranslated-text-Regenrate-all-ODDs-EN](https://user-images.githubusercontent.com/8056045/95114376-1f588e80-0744-11eb-94f9-40a237ce0ace.png)

### Filter CZ
![Untranslated-text-Filter-CZ](https://user-images.githubusercontent.com/8056045/95114371-1e276180-0744-11eb-9811-25f8fc1855a7.png)

### Filter EN
![Untranslated-text-Filter-EN](https://user-images.githubusercontent.com/8056045/95114373-1ebff800-0744-11eb-8649-1df0a5476581.png)

**Comment by tuurma** [comment]
Thanks, Boris!

**Comment by tuurma** [comment]
Missing labels added in https://github.com/eeditiones/tei-publisher-components/commit/40c7788d83b5bdef8c79815db3025937c953425b
