### ISSUE TITLE
facets selection

### ISSUE THREAD

**Issue by tuurma** [eeditiones/tei-publisher-app#33]
Current UI does not support selecting multiple facet values for single dimension, while it is supported server-side, e.g. query for documents in test collection in English or German language `collection=test&facet-language=en&facet-language=de`

![image](https://user-images.githubusercontent.com/449468/97722097-8874bd00-1aca-11eb-86b1-f5c5e8826cfc.png)

**Comment by tuurma** [comment]
/estimate 1d

Required solution would distinguish between two main use cases:

* sending query on every change (current); downside: only one value per facet dimension can be chosen via UI
* sending query only after explicit user action via Submit/Apply button; downside: additional action on the user and possibility to select mutually exclusive criteria, for which no matches exist

**Comment by tuurma** [comment]
* use tei-publisher-webcomponent >= 1.12.0
* add a button to the `searchButton` slot of `pb-custom-form`
* connect with `pb-search` or `pb-browse-docs` via `subforms` property
* remove any js triggering pb-custom-form submission on change 

```html
   <pb-custom-form id="facets" url="api/search/facets" event="pb-results-received" subscribe="docs" emit="docs">
          <paper-button slot="searchButton"><iron-icon icon="icons:search"/>submit</paper-button>                                        
   </pb-custom-form>
<pb-browse-docs ... subforms="pb-custom-form">
...

...
        // Uncomment to have facet selection change immediately trigger search
        // const facets = document.getElementById('facets');
        // if (facets) {
  //     facets.addEventListener('pb-custom-form-loaded', function(ev) {
....
```

**Comment by daliboris** [comment]
I think, the last code snipped should look this way:

`<pb-browse-docs ... subforms="#facets">`

See how `@subforms` attribute is used in this [tutorial](https://faq.teipublisher.com/api/tutorial/webcomponent/) by @wolfgangmm

**Comment by daliboris** [comment]
My code snippet for multiple facet values selection with these features:

1. `Search` button to use selected values of facets
2. `Reset` button to reset all selected values and use search without facets
3. un/checking `Show all` triggers new request to the server (you don't need to press `Search` button)

```xml
<pb-custom-form id="facets" url="api/lex/search/facets" subscribe="docs" event="pb-results-received" emit="docs" />
<div class="search-buttons">
  <paper-button id="search-reset-button" slot="resetButton"><pb-i18n key="search.reset"></pb-i18n></paper-button>
  <paper-button id="search-search-button" slot="searchButton"><pb-i18n key="search.search"></pb-i18n></paper-button>
</div
```

```javascript
const facets = document.getElementById('facets');
const reset = document.getElementById('search-reset-button');
if (facets) { 
    facets.addEventListener('pb-custom-form-loaded', function(ev) {
        const elems = ev.detail.querySelectorAll('.facet');
        elems.forEach(facet =&gt; {
            facet.addEventListener('change', () =&gt; {
                const heading = facet.closest('h3');
                if (heading) {
                    facets._submit();
                }
            });
        });
    });
    if(reset) {
        reset.addEventListener('click', () =&gt; {
            const elems = facets.querySelectorAll('.facet');
            elems.forEach(facet =&gt; { 
                const table = facet.closest('table');
                if (table) { 
                    facet.checked = false;
                    const nested = table.querySelectorAll('.nested .facet').forEach(nested =&gt; {
                        if (nested != facet) {
                            nested.checked = false;
                        }
                    });
                }
            });
            facets._submit();
        });
    }
}
```
