### ISSUE TITLE
Log in : can't use eXist-db account 'admin' (with the password as empty)

### ISSUE THREAD

**Issue by whalekeykeeper** [eeditiones/tei-publisher-app#37]
I use `admin` as the username without password to log in to the eXist-db app.
After launching the TEI-publisher page, I tried to log in with the same username-password pair and failed.

The error message is:`Wrong password or invalid user (must be member of group tei).`

Though it is said that `default user: 'Login to upload files       ######or see administrative functions (default user: 'tei-demo', password: 'demo')`, I feel it is more convenient and reasonable to allow to use `admin` without password to log in.

**Comment by wolfgangmm** [comment]
Currently TEI Publisher indeed requires that the logged in user is a member of group tei. It may make sense to add members of "dba", the group of database admins. I'll look into that.

**Comment by whalekeykeeper** [comment]
I went to `User Manager` on the dashboard with logged in as "admin", tried to set "tei-demo" and other users as members of "Member of groups", whenever I clicked `save` button,  the following error occurred:
`Server responded: 500 - Server Error`

**Comment by tuurma** [comment]
Changing group membership is a dashboard issue, not TEI Publisher.
