### ISSUE TITLE
Undefined error after clicking save button

### ISSUE THREAD

**Issue by whalekeykeeper** [eeditiones/tei-publisher-app#38]
I was following the [YouTube workshop](https://www.youtube.com/watch?v=QuWrfAS2SWM&t=13s) to learn how to use TEI-publisher.
When I was editing ODD for a file I uploaded in the "playground" section, I had to log out, log in, then click the "save" button at the left-top corner. Otherwise, an error window would jump out, with only `Error-undefined-CLOSE` as a message. After a day, even this method didn't work anymore. No matter using the `tei-demo` account or a user account I created myself in `User Manager` in eXist-db dashboard, I can not save any element after creating/modifying a model or a model sequence. The error message itself does not give me any useful information.
![Screen Shot 2021-02-16 at 3 27 06 AM](https://user-images.githubusercontent.com/46596921/108012027-a1b56100-7008-11eb-8e11-1df06358ddec.png)

**Comment by wolfgangmm** [comment]
Could you check in eXide what the permissions are for the ODD you are trying to save as well as for the generated files in `/db/tei-publisher/transform`? I assume that in the process a wrong owner or permissions were applied.

![image](https://user-images.githubusercontent.com/607433/108113224-85143a00-7097-11eb-9b01-f9d8678e4a1a.png)

**Comment by whalekeykeeper** [comment]
Hi, I tried both accounts "tei-demo" and "tei", for both tei-publisher and eXide. 
Same error.
Following are the pictures when I logged in as "tei":
![Screen Shot 2021-02-19 at 10 20 01 AM](https://user-images.githubusercontent.com/46596921/108484681-5e732080-729c-11eb-9432-00b1395f0921.png)
![Screen Shot 2021-02-19 at 10 20 25 AM](https://user-images.githubusercontent.com/46596921/108484718-67fc8880-729c-11eb-8340-c48bbda22bf1.png)
