### ISSUE TITLE
Error message is not useful after generating app

### ISSUE THREAD

**Issue by whalekeykeeper** [eeditiones/tei-publisher-app#42]
After clicking `App Generator` , filled the table, and clicked `SAVE/GENERATE` button, then I went to the dashboard, opened the app, logged in, uploaded exactly the same `.xml` file I used with creating odd and template earlier, the following error message showed up without conveying any useful information.

<img width="446" alt="Screen Shot 2021-03-15 at 8 33 17 PM" src="https://user-images.githubusercontent.com/46596921/111210627-bec05e00-85cd-11eb-8355-ed3cbbd05e98.png">

**Comment by tuurma** [comment]
Difficult to reproduce, closing until more information is provided
