### ISSUE TITLE
Untranslated text within browse.xql module

### ISSUE THREAD

**Issue by daliboris** [eeditiones/tei-publisher-app#76]
Hello, I've found untranslated text within (generated) `lib/browse.xql` file, function `app:dispatch-action($node as node(), $model as map(*), $action as xs:string?)`.

`TEI Publisher 7.1.0 / web components 1.24.18 / API 1.0.0`

See these lines of code
l. 217:
```html
<p>Removed {count($docs) - count($result)} documents.</p>
```

l. 224:
```html
<p>Removed {count($docs)} documents.</p>
```

Here is a print screen of localized list of documents with removed item:

![vivaldi_3ZayZbFZ4l](https://user-images.githubusercontent.com/8056045/144187618-bf227fc0-c5d6-4bcb-9cf7-2e99df3b2294.png)

Btw. more appropriate text would be `Removed 1 document(s).` Or `Removed documents: 1.` The latter one is more suitable for the localization.

**Comment by windauer** [comment]
got fixed with https://github.com/eeditiones/tei-publisher-components/commit/259d3087ce8957951e21266e046c91c63c0b48da and https://github.com/eeditiones/tei-publisher-app/commit/7dbd134b1a1093f0ac7afa886029fef8e585a6c1 . Translations for other languages then english are still missing.

**Comment by daliboris** [comment]
Please, can you update TEI Publisher project on https://crowdin.com, @tuurma?
